version: "3.5"

services:
  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    volumes:
      - "./data/redis:/data"
    expose:
      - 6379
  ml_modul:
    container_name: ml_modul
    build: img_sgm_ml
    environment:
      - MODEL_DIR=/data/models
      - RQ_QUEUE_NAME=default
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DOCKER=TRUE
    ports:
      - 9090:9090
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - "./data/server:/data"
      - "./logs:/tmp"
  labeltool:
    container_name: labeltool
    build: img_sgm
    ports:
      - 8080:8080
    volumes:
      - "./img_sgm:/img_sgm"