FROM python:3.7
RUN pip install label-studio==0.8.0 --no-cache-dir --default-timeout=100

CMD ["label-studio", "start", "img_sgm"]
#, "--host", "labeltool",  "--protocol", "http://", "--port", "8080"]